# Site settings
title: What Works
subtitle: Weaving Mentoring into Teaching, Research, and Service
email: whatworks@knowinnovation.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whatworks.hub.ki" # the base hostname & protocol for your site
author: Knowinnovation


# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# Social settings
website_url: http://www.knowinnovation.com
twitter_url: https://twitter.com/knowinnovation

# Build settings
markdown: kramdown

sass:
  style: compressed
