# Site settings
title: What Works
subtitle: Weaving Mentoring into Teaching, Research, and Service
email: whatworks@knowinnovation.com
description:
baseurl: "/what-works" # the subpath of your site, e.g. /blog
url: "https://knowinnovation.github.io/" # the base hostname & protocol for your site
author: Knowinnovation


# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
website_url: http://www.knowinnovation.com
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

sass:
  style: compressed
