---
title: What Works
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Weaving Mentoring into Teaching, Research, and Service
email: whatworks@knowinnovation.com
description: 
baseurl: ''
url: http://whatworks.hub.ki
author: Knowinnovation
tiles-source: pages
tiles-count: 4
website_url: http://www.knowinnovation.com
twitter_url: https://twitter.com/knowinnovation
markdown: kramdown
sass:
  style: compressed
